### ISSUE TITLE
Add party info to candidate information API

### ISSUE THREAD

**Issue by HelloYeew** [HelloYeew/sankasaint-ec#11]
# Tasks

- In both Django REST framework and frontend, add party detail that candidate in to the candidate related API.
- Update API documentation

**Comment by SainTurDaY27** [comment]
James Dr No From Russia with Love Goldfinger Thunderball You Only Live Twice On Her Majesty’s Secret Service Diamonds Are Forever Live and Let Die The Man with the Golden Gun The Spy Who Loved Me Moonraker For Your Eyes Only Octopussy A View to a Kill The Living Daylights Licence to Kill Golden Eye Tomorrow Never Dies The World Is Not Enough Die Another Day Casino Royale Bond

Anyway, @HelloYeew fixed it from discussion.
