### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by HelloYeew** [HelloYeew/sankasaint-ec#3]
Add all documentation-related project to the wiki.

**Comment by sittipat-chandang** [comment]
**Three pages added to the wiki**
1. [Home](https://github.com/HelloYeew/sankasaint-ec/wiki) - Provides an overview of our group.
2. [Configuration Management](https://github.com/HelloYeew/sankasaint-ec/wiki/Configuration-Management) - Configuration Management documentation.
3. [Link Hub](https://github.com/HelloYeew/sankasaint-ec/wiki/Link-Hub) - Contains link to external documents.

Please review these changes, thank you.

**Comment by HelloYeew** [comment]
That's looking good initially, closing as complete.
