### ISSUE TITLE
Fix block election creation if there are already ongoing election there still not working

### ISSUE THREAD

**Issue by HelloYeew** [HelloYeew/sankasaint-ec#43]
The `NewElection.objects.filter(start_date__gte=timezone.now(), end_date__lt=timezone.now())` cannot even catch the ongoing election that's why user can still create the election.

![image](https://user-images.githubusercontent.com/68165621/202522842-3131096d-2db3-4d0f-bd65-901c3364096f.png)

![image](https://user-images.githubusercontent.com/68165621/202523203-ed8c468c-2fcd-4b34-b0d5-70cb571a8c29.png)

**Comment by HelloYeew** [comment]
@pontakornth please close this if already fix

**Comment by pontakornth** [comment]
I think it's fixed in another commit already. The condition is inverted.
